name: Generate Calendar SVG/PNG

on:
  workflow_dispatch:

jobs:
  generate-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install libvips
        run: sudo apt-get update && sudo apt-get install -y libvips

      - name: Install Python dependencies
        run: |
          pip install pyvips
          pip install requests

      - name: Fetch data from Google Apps Script
        env:
          GAS_DEPLOY_URL: ${{ secrets.GAS_DEPLOY_URL }}
        run: |
          python <<EOF
          import requests
          import json
          
          gas_url = '${{ secrets.GAS_DEPLOY_URL }}'
          
          try:
              response = requests.get(gas_url)
              response.raise_for_status()
              data = response.json()
              
              with open('vacation_data.json', 'w', encoding='utf-8') as f:
                  json.dump(data, f, ensure_ascii=False, indent=2)
              
              print("Successfully fetched data and saved to vacation_data.json")
          except requests.exceptions.RequestException as e:
              print(f"Error fetching data from GAS: {e}")
              exit(1)
          except json.JSONDecodeError as e:
              print(f"Error decoding JSON from GAS: {e}")
              print(f"Response content: {response.text}")
              exit(1)
          EOF

      - name: Run Python script to generate images
        run: python my_calendar.py

      - name: Verify generated files
        run: ls -al

      - name: Commit and push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add calendar.svg calendar.png
          git commit -m "Add generated calendar images"
          git push
