name: Generate Calendar SVG/PNG

on:
  workflow_dispatch:

jobs:
  generate-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies for rendering
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ipaexfont-gothic libcairo2-dev libfreetype6-dev libpixman-1-dev
          
      - name: Install Python dependencies
        run: |
          pip install requests cairosvg

      - name: Fetch data from Google Apps Script
        env:
          GAS_DEPLOY_URL: ${{ secrets.GAS_DEPLOY_URL }}
        run: |
          python <<EOF
          import requests
          import json
          
          gas_url = '${{ secrets.GAS_DEPLOY_URL }}'
          
          try:
              response = requests.get(gas_url)
              response.raise_for_status()
              data = response.json()
              
              with open('vacation_data.json', 'w', encoding='utf-8') as f:
                  json.dump(data, f, ensure_ascii=False, indent=2)
              
              print("Successfully fetched data and saved to vacation_data.json")
          except requests.exceptions.RequestException as e:
              print(f"Error fetching data from GAS: {e}")
              exit(1)
          except json.JSONDecodeError as e:
              print(f"Error decoding JSON from GAS: {e}")
              print(f"Response content: {response.text}")
              exit(1)
          EOF

      - name: Run Python script to generate images
        run: python my_calendar.py
        
      - name: Debug List all files
        run: ls -al

      - name: Commit and push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # 生成物をすべてステージ（未追跡ファイル含む）
          git add -A

          # ステージ済み差分が無ければ終了（未追跡も含めて判定）
          if git diff --cached --quiet; then
            echo "No changes to commit. Exiting successfully."
            exit 0
          fi

          # リモート更新を取り込んでからコミット & プッシュ
          git pull --rebase origin "${GITHUB_REF_NAME:-${GITHUB_HEAD_REF:-main}}" || true
          git commit -m "Add/update generated calendar images and data"
          git push origin HEAD
