name: Generate Rolling 4-Week Calendar

on:
  workflow_dispatch: {}

jobs:
  generate-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies for rendering
        run: |
          sudo apt-get update
          # 日本語フォント（文字化け対策）
          sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra fonts-ipaexfont-gothic \
                                  libcairo2-dev libfreetype6-dev libpixman-1-dev
          fc-cache -f -v

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests cairosvg

      - name: Fetch data from Google Apps Script
        env:
          GAS_DEPLOY_URL: ${{ secrets.GAS_DEPLOY_URL }}
        run: |
          python - << 'PY'
          import json, os, sys, requests
          url = os.environ.get("GAS_DEPLOY_URL")
          if not url:
            print("GAS_DEPLOY_URL is not set; creating empty vacation_data.json")
            with open("vacation_data.json","w",encoding="utf-8") as f:
              json.dump([], f, ensure_ascii=False, indent=2)
            sys.exit(0)
          r = requests.get(url, timeout=30)
          r.raise_for_status()
          data = r.json()
          with open("vacation_data.json","w",encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
          print("Saved vacation_data.json with", len(data), "items.")
          PY

      - name: Generate rolling 4-week calendar (SVG/PNG)
        run: |
          python my_calendar.py
          ls -l calendar.*

      - name: Commit and push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit. Exiting successfully."
            exit 0
          fi

          git pull --rebase origin "${GITHUB_REF_NAME:-${GITHUB_HEAD_REF:-main}}" || true
          git commit -m "Update rolling 4-week calendar (SVG/PNG)"
          git push origin HEAD
