name: Post Calendar to Slack (8AM JST)

on:
  schedule:
    # 毎日 23:00 UTC = 日本時間 翌日 08:00
    - cron: '0 23 * * *'
  # 手動実行も残したい場合はコメント解除
  # workflow_dispatch: {}

jobs:
  post-to-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Ensure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Check calendar image exists
        run: |
          if [ ! -f "calendar.png" ]; then
            echo "calendar.png not found. Exiting without error."
            exit 0
          fi

      - name: Post calendar.png to Slack (new upload API)
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}   # xoxb- から始まるBot Token（scopes: chat:write, files:write）
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }} # 例: C0123456789
          FILE_PATH: calendar.png
          FILE_TITLE: "Rolling 4-week calendar"
        run: |
          python post_to_slack.py
